# Generated by Django 5.2.1 on 2025-05-20 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('branch', models.CharField(max_length=10)),
                ('semester', models.PositiveSmallIntegerField()),
                ('section', models.CharField(max_length=5)),
                ('number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daa', models.PositiveIntegerField(blank=True, null=True)),
                ('java', models.PositiveIntegerField(blank=True, null=True)),
                ('python', models.PositiveIntegerField(blank=True, null=True)),
                ('cpp', models.PositiveIntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.students', to_field='roll')),
            ],
        ),
    ]
