# Generated by Django 5.2.1 on 2025-05-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_students_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='Average',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
