# Generated by Django 5.2.1 on 2025-05-20 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_marks_average'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='Average',
            new_name='average',
        ),
    ]
