# Generated by Django 5.2.1 on 2025-05-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_rename_average_marks_average'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='student',
            new_name='roll',
        ),
    ]
